/*
 * Copyright (C) 2019 Michael Joyce
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 * Place, Suite 330, Boston, MA 02111-1307 USA
 */

package ca.nines.alfred.cmd;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.io.IOUtils;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;

/**
 * List the available stop word files or list the contents of one or more stop word files.
 */
@ca.nines.alfred.cmd.CommandInfo(name = "sw", description = "Show info about stop word lists")
public class StopWords extends Command {

    /**
     * Path to the stop words resource files.
     */
    public static final String PATH = "stopwords";

    /**
     * Fetch a list of the stop words files from the index generated by maven.
     *
     * @return list of files
     * @throws IOException if an error occurs.
     */
    private List<String> listStopWordFiles() throws IOException {
        InputStream in = this.getClass().getResourceAsStream("/stopwords/index");
        return IOUtils.readLines(in, StandardCharsets.UTF_8);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void execute(CommandLine cmd) throws Exception {
        String[] arguments = getArgList(cmd);
        if(arguments.length > 0) {
            for(String name : arguments) {
                out.println("Word list " + name + " contents:");
                InputStream in = this.getClass().getResourceAsStream("/" + PATH + "/" + name);
                for(String line : IOUtils.readLines(in, StandardCharsets.UTF_8)) {
                    if (line.startsWith("#")) {
                        continue;
                    }
                    out.println(line);
                }
            }
        } else {
            out.println("Stop word lists available:");
            for(String name : listStopWordFiles()) {
                if(name.trim().isEmpty()) {
                    continue;
                }
                out.println("  " + name);
            }
        }
    }
}
